### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by Daggerbot** [Daggerbot/pipeman#2]
* [ ] Render a triangle
* [ ] Load and dump tilesets
* [ ] Render tile maps
* [ ] Load, dump, and render game maps
